name: ai_calorie_tracker
description: "AI-powered Calorie Tracker using Gemini + FastAPI"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # ✅ HTTP calls to FastAPI
  http: ^1.2.1


  # ✅ State management
  flutter_riverpod: ^2.4.0

  # ✅ Local data storage (e.g., JWT tokens)
  shared_preferences: ^2.2.2

  # ✅ Environment variables (.env for base URL, API key)
  flutter_dotenv: ^5.2.1

  # ✅ UI
  intl: ^0.19.0  # Optional, for date formatting

  provider: ^6.1.1
  flutter_animate: ^4.2.0
  device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env

